### ISSUE TITLE
Add input/output example to README.md

### ISSUE THREAD

**Issue by ai** [vitkarpov/postcss-host#1]
Tomorrow I will start a PostCSS plugin guidelines and all plugins must have input/output examples :).

@vitkarpov

**Comment by vitkarpov** [comment]
All right. I'll make them also.

**Comment by vitkarpov** [comment]
@ai Am I right in assuming that I should include something to README?

Is [the usage section](https://github.com/vitkarpov/postcss-host#usage) not enough?

**Comment by ai** [comment]
Nope. You need input and output CSS examples too easy understand what your plugin do.

**Comment by vitkarpov** [comment]
Yep. I got now.

**Comment by vitkarpov** [comment]
@ai https://github.com/vitkarpov/postcss-host/pull/2

please, check this out

**Comment by ai** [comment]
Nice.

Also don’t forget to send PR with your plugin to PostCSS [README.md](https://github.com/postcss/postcss#plugins).

**Comment by vitkarpov** [comment]
Great!
