### ISSUE TITLE
Use PostCSS 4.1 API

### ISSUE THREAD

**Issue by TrySound** [vitkarpov/postcss-host#3]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by vitkarpov** [comment]
Yep! Made an update https://github.com/vitkarpov/postcss-host/commit/598ce7fa8d5a3449f2c0f3275224c999f74e4097

**Comment by TrySound** [comment]
Nope! Did you read [guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md)?
You forget about postcss.plugin API

**Comment by ai** [comment]
@vitkarpov

**Comment by ai** [comment]
@vitkarpov do not forget about `postcss.plugin()` in code ;)

**Comment by vitkarpov** [comment]
@TrySound @ai I thinks it's ok now

**Comment by ai** [comment]
yeap, thanks :)
